//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.MMDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MembersEntities : DbContext
    {
        public MembersEntities()
            : base("name=MembersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<MemberImportLog> MemberImportLogs { get; set; }
        public virtual DbSet<MemberLastImportLog> MemberLastImportLogs { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
    }
}
