//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.MMDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Query { get; set; }
        public string MailUpGroupID { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
