//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembersManager.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int ID { get; set; }
        public string ProfileID { get; set; }
        public Nullable<int> SegmentID { get; set; }
        public bool OptIn { get; set; }
    }
}
