//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembersManager.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileDetail
    {
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public string SegmentId { get; set; }
        public Nullable<bool> OptIn { get; set; }
        public Nullable<System.DateTime> OptInDate { get; set; }
    }
}
