//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembersManager.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipientSegment
    {
        public int RecipientId { get; set; }
        public int SegmentId { get; set; }
        public Nullable<bool> OptIn { get; set; }
        public Nullable<System.DateTime> OptInDate { get; set; }
    
        public virtual Recipient Recipient { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
